### ISSUE TITLE
Dataset I/O interface causes error on Beta

### ISSUE THREAD

**Issue by jamespshields** [pilrhealth/pilrhealth-issues#147]
On the beta web server, clicking the name of a dataset on the Dataset I/O developer interface causes tomcat to respond with http status 500. This corresponds to the following error in stacktrace.log:

2015-01-09 17:24:04,101 [http-bio-8080-exec-10] ERROR StackTrace  - Full Stack Trace:
com.mongodb.MongoException: too much data for sort() with no index.  add an index or specify a smaller limit
        at com.mongodb.MongoException.parse(MongoException.java:82)
        at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:292)
        at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
        at com.mongodb.DBCursor._check(DBCursor.java:368)
        at com.mongodb.DBCursor._hasNext(DBCursor.java:459)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
        at gsp_s4r_datasetTracking_rawData_gsp.run(gsp_s4r_datasetTracking_rawData_gsp.groovy:21)
        at gsp_s4r_datasetTrackinglist_gsp$_run_closure2.doCall(gsp_s4r_datasetTrackinglist_gsp.groovy:58)
        at gsp_s4r_datasetTrackinglist_gsp.run(gsp_s4r_datasetTrackinglist_gsp.groovy:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2015-01-09 17:24:04,101 [http-bio-8080-exec-10] ERROR StackTrace  - Full Stack Trace:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: too much data for sort() with no index.  add an index or specify a smaller limit
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: too much data for sort() with no index.  add an index or specify a smaller limit
        at gsp_s4r_datasetTrackinglist_gsp$_run_closure2.doCall(gsp_s4r_datasetTrackinglist_gsp.groovy:58)
        at gsp_s4r_datasetTrackinglist_gsp.run(gsp_s4r_datasetTrackinglist_gsp.groovy:63)
        ... 6 more
Caused by: com.mongodb.MongoException: too much data for sort() with no index.  add an index or specify a smaller limit
        at com.mongodb.MongoException.parse(MongoException.java:82)
        at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:292)
        at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:273)
        at com.mongodb.DBCursor._check(DBCursor.java:368)
        at com.mongodb.DBCursor._hasNext(DBCursor.java:459)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
        at gsp_s4r_datasetTracking_rawData_gsp.run(gsp_s4r_datasetTracking_rawData_gsp.groovy:21)
        ... 8 more

Looks like an index needs to be created for whatever field this controller is trying to sort on.

**Comment by jamespshields** [comment]
The controller is DatasetTrackingController.list(Dataset dataset) which specifies:
    params.sort = "dateReceived"

It would probably be a good idea to enforce the existence of an index for dateProcessed as well, if this isn't being done already.
